-- 코드를 입력하세요
SELECT CAR_ID, ROUND(SUM(DATEDIFF(END_DATE,START_DATE)+1) / COUNT(*),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 GROUP BY CAR_ID
                 HAVING SUM(DATEDIFF(END_DATE,START_DATE)+1)/COUNT(*) >= 7
                )
GROUP BY CAR_ID
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC